
# The name of your website.
name: Consumed by saturdayxiii

description:

  # Description of your site. This will show up in google.
  meta: This is my personal consumption blog. Whether it be movies, shows, games, or actual food; if it has my attention I hope to feature it here.

  # Description of your site. This will show up on the front page.
  subtitle: This is my personal consumption blog. Whether it be movies, shows, games, or actual food; if it has my attention I hope to feature it here.

author:
  name: saturdayxiii

  # Necessary for contact page
  email: 

  # Optional text (html) to display after author name. Leave empty if you don't
  # want it.
  info:

url: http://saturdayxiii.github.io
baseurl: / #"/holo-alfa"

# language attribute in <html> element.
lang: en

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############

# If you want to show the subtitle anywhere else than the front page, use
# {% include subtitle.html %} to include it anywhere you want.
show-subtitle: false
display-social-icons: true
# If you want social links to open in a new tab, set this as true
social-icons-open-newtab: true

footer-text: Peers:<br><a href="http://www.jefferysutherland.com" target="_blank">Jeffery Sutherland</a> / Oh that's it.

# Preferably 64px in height. Leave empty = disable.
logo-image: # /img/logo.png

# Toolbar color for Chrome on Android.
theme-color-attr: "#00f0ff"

# Color of Microsoft live Tile.
ms-tile-color: "#00f0ff"

# Color used throughout the theme. Format: R, G, B.
theme-color: 200, 0, 122 # Original: 0, 240, 255

# Text color used throughout the theme. Format: R, G, B.
text-color: 255, 255, 255 # Original: 0, 0, 0

# Background color used throughout the theme. Format: R, G, B.
# Note: if you change the background color AND you use cover images, you should
#       also change the CSS gradient in "_includes\gradient.css" to match the
#       background color. Edit and copy it from here:
#       http://www.colorzilla.com/gradient-editor/#ffffff+0,ffffff+100&0+0,1+100
background-color: 0, 0, 0 # Original: 255, 255, 255

display-author-post-page: true
display-author-front-page: false

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
date_format: "%b %-d, %Y"

# Minimal screen-width after which the navigation will change position from
# vertical to horizontal.
nav-breaking-point: 520px

# Number of posts on each page.
paginate: 5

# Display links for the previous and next post on post pages.
display-next-prev-post: false

# Leave empty if you don't want comments on post pages.
disqus-shortname: saturdayxiii


################
# SOCIAL ICONS #
################

# Use a complete url here, including http:// and such. Requiring just usernames
# has been considered, but this is way more customizable.
twitter: https://twitter.com/Saturdaythe13th
itch: https://saturdayxiii.itch.io/
lastfm: https://www.last.fm/user/saturdayxiii
exophase: https://www.exophase.com/user/saturdayxiii
trakt: https://trakt.tv/users/saturdayxiii
twitch: https://www.twitch.tv/saturdayxiii
youtube: https://www.youtube.com/channel/UCrtnBAX5sIDnSscqTR4KqQQ
deviantart: https://www.deviantart.com/saturdaythe13th
untappd: https://untappd.com/user/saturdayxiii
instagram: https://www.instagram.com/saturdayxiii/
tumblr: https://saturdayxiii.tumblr.com
facebook: https://www.facebook.com/SSXIII/
google-plus:
reddit: https://www.reddit.com/user/saturdayxiii
soundcloud: https://soundcloud.com/saturdayxiii
medium:
linkedin:
github:
behance:
codepen:
dribbble:
trello:
stack-overflow:
bitcoin:
paypal:


#####################
# CUSTOMIZABLE TEXT #
#####################

# Useful for translating into other languages.

var_on_the_web: other hubs
var_read: Read # Text after each post summary on the homepage.
var_newer: Newer
var_older: Older
var_next_post: Next post
var_previous_post: Previous post
var_less_than_a_minute_read: Less than a minute read
var_min_read: min read # Text after reading time. Example: 5 min read.
var_post_by: Post by
var_guest_post_by: Guest post by
var_your_email: Your email
var_your_message: Your message


##################
# BUILD SETTINGS #
##################

# You don't have to change these.

#encoding: utf-8
exclude: [vendor]
highlighter: rouge
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty #maybe /:tags/:title/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"

plugins:
  - tag_generator
